// Java
// Runnable version of the "Lazy / infinite list" concept snippet.
// Pure javac/java — no external dependencies.
//
// Quick start:
//   ./run.sh
//
// Or manually:
//   javac Main.java
//   java  Main
import java.util.stream.Stream;

public class Main {
  public static void main(String[] args) {
    // An infinite lazy list of Fibonacci numbers, generated by call-by-need.
    // Stream.iterate only records the seed pair and the successor function —
    // nothing is computed until a terminal operation pulls values through.
    Stream<long[]> fibPairs = Stream.iterate(
        new long[] {0, 1},                       // seed: (F0, F1)
        pair -> new long[] {pair[1], pair[0] + pair[1]} // next: (F1, F0+F1)
    );

    // Lazy pipeline: map projects each pair to its first element (the Fibonacci
    // number). This stage is just a recipe — it runs only as values are demanded.
    fibPairs
        .map(pair -> {
          // Visible proof of laziness: this prints exactly 10 times, not infinitely.
          System.out.println("computing Fibonacci number " + pair[0]);
          return pair[0];
        })
        // limit bounds the otherwise-infinite source to the first 10 elements.
        .limit(10)
        // forEach is the terminal operation that drives the pipeline one value at a time.
        .forEach(fib -> System.out.println("got " + fib));
  }
}
