// Shared dataset for the algorithms list and the language-specific solve
// checklists. Loaded as a plain script before each page's own script, so DATA,
// diffLabel and diffClass are available as globals.

// Human-readable label and colour class for each difficulty key.
const diffLabel = { beginner:'Beginner', easy:'Easy', easymedium:'Easy–Medium', medium:'Medium', mediumhard:'Medium–Hard', hard:'Hard' };
const diffClass = { beginner:'diff-beginner', easy:'diff-easy', easymedium:'diff-easymedium', medium:'diff-medium', mediumhard:'diff-mediumhard', hard:'diff-hard' };

// One entry per algorithm: name, difficulty key, technique/topic, and a stable
// slug used as the saved-progress id. An optional `page` field names a local
// detail-page folder once one has been written.
const DATA = [
  // Beginner
  {n:"Reverse a string", cat:"beginner", tech:"String", slug:"reverseastring", page:"001-reverse-a-string"},
  {n:"Check if a string is a palindrome", cat:"beginner", tech:"String / Two Pointers", slug:"palindromecheck", page:"002-check-if-a-string-is-a-palindrome"},
  {n:"Find the maximum/minimum in an array", cat:"beginner", tech:"Array", slug:"findmaxmininarray", page:"003-find-the-maximum-minimum-in-an-array"},
  {n:"Count occurrences of a character in a string", cat:"beginner", tech:"String / Hashing", slug:"countcharacteroccurrences", page:"004-count-occurrences-of-a-character-in-a-string"},
  {n:"FizzBuzz", cat:"beginner", tech:"Math / Simulation", slug:"fizzbuzz", page:"005-fizzbuzz"},
  {n:"Factorial (iterative)", cat:"beginner", tech:"Math", slug:"factorialiterative", page:"006-factorial-iterative"},
  {n:"Fibonacci (iterative)", cat:"beginner", tech:"Math / DP", slug:"fibonacciiterative", page:"007-fibonacci-iterative"},
  {n:"Sum of array elements", cat:"beginner", tech:"Array", slug:"sumofarray", page:"008-sum-of-array-elements"},
  {n:"Check if a number is prime", cat:"beginner", tech:"Math", slug:"primecheck", page:"009-check-if-a-number-is-prime"},
  {n:"Remove duplicates from an array", cat:"beginner", tech:"Array / Hashing", slug:"removeduplicatesarray", page:"010-remove-duplicates-from-an-array"},

  // Easy
  {n:"Two Sum (hash map)", cat:"easy", tech:"Hashing", slug:"twosum", page:"011-two-sum-hash-map"},
  {n:"Binary search", cat:"easy", tech:"Searching", slug:"binarysearch", page:"012-binary-search"},
  {n:"Bubble sort", cat:"easy", tech:"Sorting", slug:"bubblesort", page:"013-bubble-sort"},
  {n:"Insertion sort", cat:"easy", tech:"Sorting", slug:"insertionsort", page:"014-insertion-sort"},
  {n:"Merge two sorted arrays", cat:"easy", tech:"Two Pointers", slug:"mergetwosortedarrays", page:"015-merge-two-sorted-arrays"},
  {n:"Find missing number in 1..n", cat:"easy", tech:"Math / Bit Manipulation", slug:"missingnumber", page:"016-find-missing-number-in-1-n"},
  {n:"Reverse a linked list (iterative)", cat:"easy", tech:"Linked List", slug:"reverselinkedlistiterative", page:"017-reverse-a-linked-list-iterative"},
  {n:"Check balanced parentheses (stack)", cat:"easy", tech:"Stack", slug:"balancedparentheses", page:"018-check-balanced-parentheses-stack"},
  {n:"Selection sort", cat:"easy", tech:"Sorting", slug:"selectionsort", page:"019-selection-sort"},
  {n:"Count vowels in a string", cat:"easy", tech:"String", slug:"countvowels", page:"020-count-vowels-in-a-string"},
  {n:"Anagram check", cat:"easy", tech:"String / Hashing", slug:"anagramcheck", page:"021-anagram-check"},
  {n:"First non-repeating character", cat:"easy", tech:"String / Hashing", slug:"firstnonrepeatingcharacter", page:"022-first-non-repeating-character"},
  {n:"Move zeroes to end of array", cat:"easy", tech:"Array / Two Pointers", slug:"movezeroes", page:"023-move-zeroes-to-end-of-array"},
  {n:"Rotate an array by k steps", cat:"easy", tech:"Array", slug:"rotatearraybyk", page:"024-rotate-an-array-by-k-steps"},
  {n:"Greatest common divisor (Euclidean)", cat:"easy", tech:"Math", slug:"gcdeuclidean", page:"025-greatest-common-divisor-euclidean"},

  // Easy–Medium
  {n:"Factorial (recursive)", cat:"easymedium", tech:"Recursion", slug:"factorialrecursive", page:"026-factorial-recursive"},
  {n:"Fibonacci (recursive + memoization)", cat:"easymedium", tech:"Recursion / DP", slug:"fibonaccirecursivememo", page:"027-fibonacci-recursive-memoization"},
  {n:"Merge sort", cat:"easymedium", tech:"Sorting / Divide & Conquer", slug:"mergesort", page:"028-merge-sort"},
  {n:"Quick sort", cat:"easymedium", tech:"Sorting / Divide & Conquer", slug:"quicksort", page:"029-quick-sort"},
  {n:"Flatten a nested array", cat:"easymedium", tech:"Recursion", slug:"flattennestedarray", page:"030-flatten-a-nested-array"},
  {n:"Find all pairs that sum to a target", cat:"easymedium", tech:"Hashing / Two Pointers", slug:"pairsumtarget", page:"031-find-all-pairs-that-sum-to-a-target"},
  {n:"Longest common prefix in a string array", cat:"easymedium", tech:"String", slug:"longestcommonprefix", page:"032-longest-common-prefix-in-a-string-array"},
  {n:"Roman numeral to integer", cat:"easymedium", tech:"String / Math", slug:"romantointeger", page:"033-roman-numeral-to-integer"},
  {n:"Valid IP address check", cat:"easymedium", tech:"String", slug:"validipaddress", page:"034-valid-ip-address-check"},
  {n:"Pascal's triangle", cat:"easymedium", tech:"Array / DP", slug:"pascalstriangle", page:"035-pascal-s-triangle"},
  {n:"Power of a number (fast exponentiation)", cat:"easymedium", tech:"Math / Divide & Conquer", slug:"fastexponentiation", page:"036-power-of-a-number-fast-exponentiation"},
  {n:"Linked list cycle (Floyd's)", cat:"easymedium", tech:"Linked List / Two Pointers", slug:"linkedlistcycle", page:"037-linked-list-cycle-floyd-s"},
  {n:"Middle of a linked list", cat:"easymedium", tech:"Linked List / Two Pointers", slug:"middleoflinkedlist", page:"038-middle-of-a-linked-list"},
  {n:"Level-order traversal (BFS on a tree)", cat:"easymedium", tech:"Tree / BFS", slug:"levelordertraversal", page:"039-level-order-traversal-bfs-on-a-tree"},
  {n:"Inorder / preorder / postorder traversal (DFS)", cat:"easymedium", tech:"Tree / DFS", slug:"treedfstraversals", page:"040-inorder-preorder-postorder-traversal-dfs"},

  // Medium
  {n:"Binary search tree: insert, search, delete", cat:"medium", tech:"Tree / BST", slug:"bstoperations", page:"041-binary-search-tree-insert-search-delete"},
  {n:"Valid BST check", cat:"medium", tech:"Tree / BST", slug:"validbst", page:"042-valid-bst-check"},
  {n:"Lowest common ancestor (BST)", cat:"medium", tech:"Tree / BST", slug:"lowestcommonancestorbst", page:"043-lowest-common-ancestor-bst"},
  {n:"Diameter of a binary tree", cat:"medium", tech:"Tree / DFS", slug:"diameterofbinarytree", page:"044-diameter-of-a-binary-tree"},
  {n:"Maximum depth of a binary tree", cat:"medium", tech:"Tree / DFS", slug:"maxdepthbinarytree", page:"045-maximum-depth-of-a-binary-tree"},
  {n:"Number of islands (DFS/BFS on a grid)", cat:"medium", tech:"Graph / DFS, BFS", slug:"numberofislands", page:"046-number-of-islands-dfs-bfs-on-a-grid"},
  {n:"Clone a graph", cat:"medium", tech:"Graph / BFS, DFS", slug:"clonegraph", page:"047-clone-a-graph"},
  {n:"Product of array except self", cat:"medium", tech:"Array / Prefix", slug:"productexceptself", page:"048-product-of-array-except-self"},
  {n:"Maximum subarray (Kadane's algorithm)", cat:"medium", tech:"Array / DP", slug:"maximumsubarraykadane", page:"049-maximum-subarray-kadane-s-algorithm"},
  {n:"Container with most water (two pointers)", cat:"medium", tech:"Two Pointers", slug:"containerwithmostwater", page:"050-container-with-most-water-two-pointers"},
  {n:"3Sum", cat:"medium", tech:"Two Pointers", slug:"threesum", page:"051-3sum"},
  {n:"Sliding window maximum", cat:"medium", tech:"Sliding Window / Deque", slug:"slidingwindowmaximum", page:"052-sliding-window-maximum"},
  {n:"Longest substring without repeating characters", cat:"medium", tech:"Sliding Window", slug:"longestsubstringwithoutrepeating", page:"053-longest-substring-without-repeating-characters"},
  {n:"Group anagrams", cat:"medium", tech:"Hashing / String", slug:"groupanagrams", page:"054-group-anagrams"},
  {n:"Top K frequent elements (heap)", cat:"medium", tech:"Heap", slug:"topkfrequentelements", page:"055-top-k-frequent-elements-heap"},
  {n:"Kth largest element (quickselect)", cat:"medium", tech:"Quickselect", slug:"kthlargestelement", page:"056-kth-largest-element-quickselect"},
  {n:"Merge intervals", cat:"medium", tech:"Sorting / Intervals", slug:"mergeintervals", page:"057-merge-intervals"},
  {n:"Jump game (greedy)", cat:"medium", tech:"Greedy", slug:"jumpgame", page:"058-jump-game-greedy"},
  {n:"Coin change (DP – minimum coins)", cat:"medium", tech:"Dynamic Programming", slug:"coinchange", page:"059-coin-change-dp-minimum-coins"},
  {n:"Climbing stairs (DP)", cat:"medium", tech:"Dynamic Programming", slug:"climbingstairs", page:"060-climbing-stairs-dp"},
  {n:"House robber (DP)", cat:"medium", tech:"Dynamic Programming", slug:"houserobber", page:"061-house-robber-dp"},
  {n:"Unique paths (DP)", cat:"medium", tech:"Dynamic Programming", slug:"uniquepaths", page:"062-unique-paths-dp"},
  {n:"0/1 Knapsack (DP)", cat:"medium", tech:"Dynamic Programming", slug:"knapsack01", page:"063-0-1-knapsack-dp"},
  {n:"Longest common subsequence (DP)", cat:"medium", tech:"Dynamic Programming", slug:"longestcommonsubsequence", page:"064-longest-common-subsequence-dp"},
  {n:"Decode ways (DP)", cat:"medium", tech:"Dynamic Programming", slug:"decodeways", page:"065-decode-ways-dp"},

  // Medium–Hard
  {n:"Course schedule (topological sort / cycle detection)", cat:"mediumhard", tech:"Graph / Topological Sort", slug:"courseschedule", page:"066-course-schedule-topological-sort-cycle-detection"},
  {n:"Dijkstra's shortest path", cat:"mediumhard", tech:"Graph / Shortest Path", slug:"dijkstrashortestpath", page:"067-dijkstra-s-shortest-path"},
  {n:"Bellman-Ford algorithm", cat:"mediumhard", tech:"Graph / Shortest Path", slug:"bellmanford", page:"068-bellman-ford-algorithm"},
  {n:"Floyd-Warshall algorithm", cat:"mediumhard", tech:"Graph / Shortest Path", slug:"floydwarshall", page:"069-floyd-warshall-algorithm"},
  {n:"Prim's MST", cat:"mediumhard", tech:"Graph / MST", slug:"primsmst", page:"070-prim-s-mst"},
  {n:"Kruskal's MST (Union-Find)", cat:"mediumhard", tech:"Graph / Union-Find", slug:"kruskalsmst", page:"071-kruskal-s-mst-union-find"},
  {n:"Trie: insert, search, starts-with", cat:"mediumhard", tech:"Trie / Design", slug:"trie", page:"072-trie-insert-search-starts-with"},
  {n:"LRU Cache", cat:"mediumhard", tech:"Design", slug:"lrucache", page:"073-lru-cache"},
  {n:"LFU Cache", cat:"mediumhard", tech:"Design", slug:"lfucache", page:"074-lfu-cache"},
  {n:"Serialize and deserialize a binary tree", cat:"mediumhard", tech:"Tree / Design", slug:"serializedeserializebinarytree", page:"075-serialize-and-deserialize-a-binary-tree"},
  {n:"Reconstruct binary tree from traversals", cat:"mediumhard", tech:"Tree / Recursion", slug:"reconstructtreefromtraversals", page:"076-reconstruct-binary-tree-from-traversals"},
  {n:"Flatten a binary tree to linked list", cat:"mediumhard", tech:"Tree", slug:"flattentreetolinkedlist", page:"077-flatten-a-binary-tree-to-linked-list"},
  {n:"Binary search on answer (e.g., capacity to ship)", cat:"mediumhard", tech:"Binary Search", slug:"binarysearchonanswer", page:"078-binary-search-on-answer-e-g-capacity-to-ship"},
  {n:"Median of two sorted arrays", cat:"mediumhard", tech:"Binary Search / Divide & Conquer", slug:"medianoftwosortedarrays", page:"079-median-of-two-sorted-arrays"},
  {n:"Longest palindromic substring (expand around center)", cat:"mediumhard", tech:"String / DP", slug:"longestpalindromicsubstring", page:"080-longest-palindromic-substring-expand-around-center"},
  {n:"Palindromic substrings count", cat:"mediumhard", tech:"String / DP", slug:"countpalindromicsubstrings", page:"081-palindromic-substrings-count"},
  {n:"Maximum product subarray", cat:"mediumhard", tech:"Array / DP", slug:"maximumproductsubarray", page:"082-maximum-product-subarray"},

  // Hard
  {n:"Trapping rain water", cat:"hard", tech:"Two Pointers / Stack", slug:"trappingrainwater", page:"083-trapping-rain-water"},
  {n:"Largest rectangle in histogram", cat:"hard", tech:"Stack", slug:"largestrectanglehistogram", page:"084-largest-rectangle-in-histogram"},
  {n:"Sliding window minimum (deque)", cat:"hard", tech:"Sliding Window / Deque", slug:"slidingwindowminimum", page:"085-sliding-window-minimum-deque"},
  {n:"Find all permutations of a string/array", cat:"hard", tech:"Backtracking", slug:"allpermutations", page:"086-find-all-permutations-of-a-string-array"},
  {n:"Find all subsets (power set)", cat:"hard", tech:"Backtracking / Bit Manipulation", slug:"powerset", page:"087-find-all-subsets-power-set"},
  {n:"Word search in a grid (backtracking)", cat:"hard", tech:"Backtracking", slug:"wordsearchgrid", page:"088-word-search-in-a-grid-backtracking"},
  {n:"N-Queens problem", cat:"hard", tech:"Backtracking", slug:"nqueens", page:"089-n-queens-problem"},
  {n:"Sudoku solver", cat:"hard", tech:"Backtracking", slug:"sudokusolver", page:"090-sudoku-solver"},
  {n:"Minimum window substring", cat:"hard", tech:"Sliding Window", slug:"minimumwindowsubstring", page:"091-minimum-window-substring"},
  {n:"Alien dictionary (topological sort)", cat:"hard", tech:"Graph / Topological Sort", slug:"aliendictionary", page:"092-alien-dictionary-topological-sort"},
  {n:"Word ladder (BFS)", cat:"hard", tech:"Graph / BFS", slug:"wordladder", page:"093-word-ladder-bfs"},
  {n:"Critical connections in a network (Tarjan's bridges)", cat:"hard", tech:"Graph / Tarjan", slug:"criticalconnections", page:"094-critical-connections-in-a-network-tarjan-s-bridges"},
  {n:"Longest increasing subsequence (DP + binary search, O(n log n))", cat:"hard", tech:"DP / Binary Search", slug:"longestincreasingsubsequence", page:"095-longest-increasing-subsequence-dp-binary-search-o-n-log-n"},
  {n:"Edit distance (Levenshtein, DP)", cat:"hard", tech:"Dynamic Programming", slug:"editdistance", page:"096-edit-distance-levenshtein-dp"},
  {n:"Burst balloons (interval DP)", cat:"hard", tech:"Dynamic Programming", slug:"burstballoons", page:"097-burst-balloons-interval-dp"},
  {n:"Regular expression matching (DP)", cat:"hard", tech:"Dynamic Programming", slug:"regexmatching", page:"098-regular-expression-matching-dp"},
  {n:"Wildcard matching (DP)", cat:"hard", tech:"Dynamic Programming", slug:"wildcardmatching", page:"099-wildcard-matching-dp"},
  {n:"Maximum flow (Ford-Fulkerson / Edmonds-Karp)", cat:"hard", tech:"Graph / Max Flow", slug:"maxflowfordfulkerson", page:"100-maximum-flow-ford-fulkerson-edmonds-karp"},
];
