// Shared dataset for the algorithms list and the language-specific solve
// checklists. Loaded as a plain script before each page's own script, so DATA,
// diffLabel and diffClass are available as globals.

// Human-readable label and colour class for each difficulty key.
const diffLabel = { beginner:'Beginner', easy:'Easy', easymedium:'Easy–Medium', medium:'Medium', mediumhard:'Medium–Hard', hard:'Hard' };
const diffClass = { beginner:'diff-beginner', easy:'diff-easy', easymedium:'diff-easymedium', medium:'diff-medium', mediumhard:'diff-mediumhard', hard:'diff-hard' };

// One entry per algorithm: name, difficulty key, technique/topic, and a stable
// slug used as the saved-progress id. An optional `page` field names a local
// detail-page folder once one has been written.
const DATA = [
  // Beginner
  {n:"Reverse a string", cat:"beginner", tech:"String", slug:"reverseastring", page:"001-reverse-a-string"},
  {n:"Check if a string is a palindrome", cat:"beginner", tech:"String / Two Pointers", slug:"palindromecheck"},
  {n:"Find the maximum/minimum in an array", cat:"beginner", tech:"Array", slug:"findmaxmininarray"},
  {n:"Count occurrences of a character in a string", cat:"beginner", tech:"String / Hashing", slug:"countcharacteroccurrences"},
  {n:"FizzBuzz", cat:"beginner", tech:"Math / Simulation", slug:"fizzbuzz"},
  {n:"Factorial (iterative)", cat:"beginner", tech:"Math", slug:"factorialiterative"},
  {n:"Fibonacci (iterative)", cat:"beginner", tech:"Math / DP", slug:"fibonacciiterative"},
  {n:"Sum of array elements", cat:"beginner", tech:"Array", slug:"sumofarray"},
  {n:"Check if a number is prime", cat:"beginner", tech:"Math", slug:"primecheck"},
  {n:"Remove duplicates from an array", cat:"beginner", tech:"Array / Hashing", slug:"removeduplicatesarray"},

  // Easy
  {n:"Two Sum (hash map)", cat:"easy", tech:"Hashing", slug:"twosum"},
  {n:"Binary search", cat:"easy", tech:"Searching", slug:"binarysearch"},
  {n:"Bubble sort", cat:"easy", tech:"Sorting", slug:"bubblesort"},
  {n:"Insertion sort", cat:"easy", tech:"Sorting", slug:"insertionsort"},
  {n:"Merge two sorted arrays", cat:"easy", tech:"Two Pointers", slug:"mergetwosortedarrays"},
  {n:"Find missing number in 1..n", cat:"easy", tech:"Math / Bit Manipulation", slug:"missingnumber"},
  {n:"Reverse a linked list (iterative)", cat:"easy", tech:"Linked List", slug:"reverselinkedlistiterative"},
  {n:"Check balanced parentheses (stack)", cat:"easy", tech:"Stack", slug:"balancedparentheses"},
  {n:"Selection sort", cat:"easy", tech:"Sorting", slug:"selectionsort"},
  {n:"Count vowels in a string", cat:"easy", tech:"String", slug:"countvowels"},
  {n:"Anagram check", cat:"easy", tech:"String / Hashing", slug:"anagramcheck"},
  {n:"First non-repeating character", cat:"easy", tech:"String / Hashing", slug:"firstnonrepeatingcharacter"},
  {n:"Move zeroes to end of array", cat:"easy", tech:"Array / Two Pointers", slug:"movezeroes"},
  {n:"Rotate an array by k steps", cat:"easy", tech:"Array", slug:"rotatearraybyk"},
  {n:"Greatest common divisor (Euclidean)", cat:"easy", tech:"Math", slug:"gcdeuclidean"},

  // Easy–Medium
  {n:"Factorial (recursive)", cat:"easymedium", tech:"Recursion", slug:"factorialrecursive"},
  {n:"Fibonacci (recursive + memoization)", cat:"easymedium", tech:"Recursion / DP", slug:"fibonaccirecursivememo"},
  {n:"Merge sort", cat:"easymedium", tech:"Sorting / Divide & Conquer", slug:"mergesort"},
  {n:"Quick sort", cat:"easymedium", tech:"Sorting / Divide & Conquer", slug:"quicksort"},
  {n:"Flatten a nested array", cat:"easymedium", tech:"Recursion", slug:"flattennestedarray"},
  {n:"Find all pairs that sum to a target", cat:"easymedium", tech:"Hashing / Two Pointers", slug:"pairsumtarget"},
  {n:"Longest common prefix in a string array", cat:"easymedium", tech:"String", slug:"longestcommonprefix"},
  {n:"Roman numeral to integer", cat:"easymedium", tech:"String / Math", slug:"romantointeger"},
  {n:"Valid IP address check", cat:"easymedium", tech:"String", slug:"validipaddress"},
  {n:"Pascal's triangle", cat:"easymedium", tech:"Array / DP", slug:"pascalstriangle"},
  {n:"Power of a number (fast exponentiation)", cat:"easymedium", tech:"Math / Divide & Conquer", slug:"fastexponentiation"},
  {n:"Linked list cycle (Floyd's)", cat:"easymedium", tech:"Linked List / Two Pointers", slug:"linkedlistcycle"},
  {n:"Middle of a linked list", cat:"easymedium", tech:"Linked List / Two Pointers", slug:"middleoflinkedlist"},
  {n:"Level-order traversal (BFS on a tree)", cat:"easymedium", tech:"Tree / BFS", slug:"levelordertraversal"},
  {n:"Inorder / preorder / postorder traversal (DFS)", cat:"easymedium", tech:"Tree / DFS", slug:"treedfstraversals"},

  // Medium
  {n:"Binary search tree: insert, search, delete", cat:"medium", tech:"Tree / BST", slug:"bstoperations"},
  {n:"Valid BST check", cat:"medium", tech:"Tree / BST", slug:"validbst"},
  {n:"Lowest common ancestor (BST)", cat:"medium", tech:"Tree / BST", slug:"lowestcommonancestorbst"},
  {n:"Diameter of a binary tree", cat:"medium", tech:"Tree / DFS", slug:"diameterofbinarytree"},
  {n:"Maximum depth of a binary tree", cat:"medium", tech:"Tree / DFS", slug:"maxdepthbinarytree"},
  {n:"Number of islands (DFS/BFS on a grid)", cat:"medium", tech:"Graph / DFS, BFS", slug:"numberofislands"},
  {n:"Clone a graph", cat:"medium", tech:"Graph / BFS, DFS", slug:"clonegraph"},
  {n:"Product of array except self", cat:"medium", tech:"Array / Prefix", slug:"productexceptself"},
  {n:"Maximum subarray (Kadane's algorithm)", cat:"medium", tech:"Array / DP", slug:"maximumsubarraykadane"},
  {n:"Container with most water (two pointers)", cat:"medium", tech:"Two Pointers", slug:"containerwithmostwater"},
  {n:"3Sum", cat:"medium", tech:"Two Pointers", slug:"threesum"},
  {n:"Sliding window maximum", cat:"medium", tech:"Sliding Window / Deque", slug:"slidingwindowmaximum"},
  {n:"Longest substring without repeating characters", cat:"medium", tech:"Sliding Window", slug:"longestsubstringwithoutrepeating"},
  {n:"Group anagrams", cat:"medium", tech:"Hashing / String", slug:"groupanagrams"},
  {n:"Top K frequent elements (heap)", cat:"medium", tech:"Heap", slug:"topkfrequentelements"},
  {n:"Kth largest element (quickselect)", cat:"medium", tech:"Quickselect", slug:"kthlargestelement"},
  {n:"Merge intervals", cat:"medium", tech:"Sorting / Intervals", slug:"mergeintervals"},
  {n:"Jump game (greedy)", cat:"medium", tech:"Greedy", slug:"jumpgame"},
  {n:"Coin change (DP – minimum coins)", cat:"medium", tech:"Dynamic Programming", slug:"coinchange"},
  {n:"Climbing stairs (DP)", cat:"medium", tech:"Dynamic Programming", slug:"climbingstairs"},
  {n:"House robber (DP)", cat:"medium", tech:"Dynamic Programming", slug:"houserobber"},
  {n:"Unique paths (DP)", cat:"medium", tech:"Dynamic Programming", slug:"uniquepaths"},
  {n:"0/1 Knapsack (DP)", cat:"medium", tech:"Dynamic Programming", slug:"knapsack01"},
  {n:"Longest common subsequence (DP)", cat:"medium", tech:"Dynamic Programming", slug:"longestcommonsubsequence"},
  {n:"Decode ways (DP)", cat:"medium", tech:"Dynamic Programming", slug:"decodeways"},

  // Medium–Hard
  {n:"Course schedule (topological sort / cycle detection)", cat:"mediumhard", tech:"Graph / Topological Sort", slug:"courseschedule"},
  {n:"Dijkstra's shortest path", cat:"mediumhard", tech:"Graph / Shortest Path", slug:"dijkstrashortestpath"},
  {n:"Bellman-Ford algorithm", cat:"mediumhard", tech:"Graph / Shortest Path", slug:"bellmanford"},
  {n:"Floyd-Warshall algorithm", cat:"mediumhard", tech:"Graph / Shortest Path", slug:"floydwarshall"},
  {n:"Prim's MST", cat:"mediumhard", tech:"Graph / MST", slug:"primsmst"},
  {n:"Kruskal's MST (Union-Find)", cat:"mediumhard", tech:"Graph / Union-Find", slug:"kruskalsmst"},
  {n:"Trie: insert, search, starts-with", cat:"mediumhard", tech:"Trie / Design", slug:"trie"},
  {n:"LRU Cache", cat:"mediumhard", tech:"Design", slug:"lrucache"},
  {n:"LFU Cache", cat:"mediumhard", tech:"Design", slug:"lfucache"},
  {n:"Serialize and deserialize a binary tree", cat:"mediumhard", tech:"Tree / Design", slug:"serializedeserializebinarytree"},
  {n:"Reconstruct binary tree from traversals", cat:"mediumhard", tech:"Tree / Recursion", slug:"reconstructtreefromtraversals"},
  {n:"Flatten a binary tree to linked list", cat:"mediumhard", tech:"Tree", slug:"flattentreetolinkedlist"},
  {n:"Binary search on answer (e.g., capacity to ship)", cat:"mediumhard", tech:"Binary Search", slug:"binarysearchonanswer"},
  {n:"Median of two sorted arrays", cat:"mediumhard", tech:"Binary Search / Divide & Conquer", slug:"medianoftwosortedarrays"},
  {n:"Longest palindromic substring (expand around center)", cat:"mediumhard", tech:"String / DP", slug:"longestpalindromicsubstring"},
  {n:"Palindromic substrings count", cat:"mediumhard", tech:"String / DP", slug:"countpalindromicsubstrings"},
  {n:"Maximum product subarray", cat:"mediumhard", tech:"Array / DP", slug:"maximumproductsubarray"},

  // Hard
  {n:"Trapping rain water", cat:"hard", tech:"Two Pointers / Stack", slug:"trappingrainwater"},
  {n:"Largest rectangle in histogram", cat:"hard", tech:"Stack", slug:"largestrectanglehistogram"},
  {n:"Sliding window minimum (deque)", cat:"hard", tech:"Sliding Window / Deque", slug:"slidingwindowminimum"},
  {n:"Find all permutations of a string/array", cat:"hard", tech:"Backtracking", slug:"allpermutations"},
  {n:"Find all subsets (power set)", cat:"hard", tech:"Backtracking / Bit Manipulation", slug:"powerset"},
  {n:"Word search in a grid (backtracking)", cat:"hard", tech:"Backtracking", slug:"wordsearchgrid"},
  {n:"N-Queens problem", cat:"hard", tech:"Backtracking", slug:"nqueens"},
  {n:"Sudoku solver", cat:"hard", tech:"Backtracking", slug:"sudokusolver"},
  {n:"Minimum window substring", cat:"hard", tech:"Sliding Window", slug:"minimumwindowsubstring"},
  {n:"Alien dictionary (topological sort)", cat:"hard", tech:"Graph / Topological Sort", slug:"aliendictionary"},
  {n:"Word ladder (BFS)", cat:"hard", tech:"Graph / BFS", slug:"wordladder"},
  {n:"Critical connections in a network (Tarjan's bridges)", cat:"hard", tech:"Graph / Tarjan", slug:"criticalconnections"},
  {n:"Longest increasing subsequence (DP + binary search, O(n log n))", cat:"hard", tech:"DP / Binary Search", slug:"longestincreasingsubsequence"},
  {n:"Edit distance (Levenshtein, DP)", cat:"hard", tech:"Dynamic Programming", slug:"editdistance"},
  {n:"Burst balloons (interval DP)", cat:"hard", tech:"Dynamic Programming", slug:"burstballoons"},
  {n:"Regular expression matching (DP)", cat:"hard", tech:"Dynamic Programming", slug:"regexmatching"},
  {n:"Wildcard matching (DP)", cat:"hard", tech:"Dynamic Programming", slug:"wildcardmatching"},
  {n:"Maximum flow (Ford-Fulkerson / Edmonds-Karp)", cat:"hard", tech:"Graph / Max Flow", slug:"maxflowfordfulkerson"},
];
